language: java
jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - gem install compass
  - npm install -g bower grunt-cli karma
  - bower install

notifications:
  slack: majimenatest:L3BPfAVyCiFEXwQ6Q2qMI7c1
